# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ekgCore, fetchgit, network, text, time
, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "ekg-statsd";
  version = "0.2.0.1";
  src = fetchgit {
    url = "https://github.com/tibbe/ekg-statsd";
    sha256 = "4cbcac81701fbc6836c16d22d5cb1a5d2d627f8e8d803f47129004e07d5a2270";
    rev = "8d679bd1782f1b7c25aafd926f601f9386090a60";
  };
  buildDepends = [ ekgCore network text time unorderedContainers ];
  meta = {
    homepage = "https://github.com/tibbe/ekg-statsd";
    description = "Push metrics to statsd";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})